---
- hosts: all
  remote_user: ubuntu
  become_user: root

  tasks:

  - name: Dependencies
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
    - curl
    - ca-certificates
    - mosh
    - software-properties-common
    - apt-transport-https
    - bridge-utils

  - name: Add key hack
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

  - name: Repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu/ xenial stable"
      state: present

  - name: Install docker-ce
    apt:
      name: docker-ce
      state: latest 
  - name: Enable debug level logging
    copy:
      src: files/daemon.json
      dest: /etc/docker/

  - name: Restart Docker
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker
