---
- hosts: all
  remote_user: ubuntu
  become_user: root

  tasks:

  - name: Download telegraf
    get_url: 
      url: "https://dl.influxdata.com/telegraf/releases/telegraf_1.3.1-1_amd64.deb"
      dest: "/tmp/telegraf_1.3.1-1_amd64.deb"

  - name: Install it
    apt: 
       deb: "/tmp/telegraf_1.3.1-1_amd64.deb"

  - name: Enable debug level logging
    copy:
      src: files/telegraf.conf
      dest: /etc/telegraf/telegraf.conf

  - name: Add telegraf to docker group
    user: 
      name: telegraf
      group: docker

  - name: Restart telegraph
    systemd:
      state: restarted
      daemon_reload: yes
      name: telegraf
