packetbeat.interfaces.device: any
packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols.icmp:
  # Enable ICMPv4 and ICMPv6 monitoring. Default: false
  enabled: true

packetbeat.protocols.dns:
  # Configure the ports where to listen for DNS traffic. You can disable
  # the DNS protocol by commenting out the list of ports.
  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 3128]

packetbeat.protocols.mysql:
  ports: [3306]

output.logstash:
  hosts: ["internal-logstash-1299266159.us-east-2.elb.amazonaws.com:5000"]
  index: "packetbeat"

#logging.level: debug
#logging.selectors: ["*"]
